-- Student Management schema (PostgreSQL). Idempotent: applied by database/seed.php on every start,
-- or by hand: psql student_management -f database/schema.sql
CREATE TABLE IF NOT EXISTS department (
  id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   VARCHAR(255) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS admin_reg (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  phone      VARCHAR(20)  NOT NULL,
  password   VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_admin_email UNIQUE (email),
  CONSTRAINT uq_admin_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS principal_reg (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  phone      VARCHAR(20)  NOT NULL,
  password   VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_principal_email UNIQUE (email),
  CONSTRAINT uq_principal_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS hod_reg (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  password      VARCHAR(255) NOT NULL,
  report_to     INT NULL,
  department_id INT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_hod_email UNIQUE (email),
  CONSTRAINT uq_hod_phone UNIQUE (phone),
  CONSTRAINT uq_hod_department UNIQUE (department_id),
  CONSTRAINT fk_hod_principal  FOREIGN KEY (report_to)     REFERENCES principal_reg (id) ON DELETE SET NULL,
  CONSTRAINT fk_hod_department FOREIGN KEY (department_id) REFERENCES department (id)    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS teacher_reg (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  password      VARCHAR(255) NOT NULL,
  report_to     INT NULL,
  department_id INT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_teacher_email UNIQUE (email),
  CONSTRAINT uq_teacher_phone UNIQUE (phone),
  CONSTRAINT fk_teacher_hod        FOREIGN KEY (report_to)     REFERENCES hod_reg (id)    ON DELETE SET NULL,
  CONSTRAINT fk_teacher_department FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL
);

-- Codes an admin hands to a new principal (checked on principal registration)
CREATE TABLE IF NOT EXISTS details (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  principal_verification VARCHAR(64) NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_details_code UNIQUE (principal_verification)
);

-- Reference data: departments (only inserted when missing)
INSERT INTO department (name, status) VALUES
  ('Computer Science', 0),
  ('Information Technology', 0),
  ('Electronics', 0),
  ('Mechanical Engineering', 0)
ON CONFLICT (name) DO NOTHING;
