-- Student Management schema (PostgreSQL). Idempotent: applied by database/seed.php on every start,
-- or by hand: psql student_management -f database/schema.sql
CREATE TABLE IF NOT EXISTS department (
  id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   VARCHAR(255) NOT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  CONSTRAINT uq_department_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS admin_reg (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  phone      VARCHAR(20)  NOT NULL,
  password   VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_admin_email UNIQUE (email),
  CONSTRAINT uq_admin_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS principal_reg (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) NOT NULL,
  phone      VARCHAR(20)  NOT NULL,
  password   VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_principal_email UNIQUE (email),
  CONSTRAINT uq_principal_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS hod_reg (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  password      VARCHAR(255) NOT NULL,
  report_to     INT NULL,
  department_id INT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_hod_email UNIQUE (email),
  CONSTRAINT uq_hod_phone UNIQUE (phone),
  CONSTRAINT uq_hod_department UNIQUE (department_id),
  CONSTRAINT fk_hod_principal  FOREIGN KEY (report_to)     REFERENCES principal_reg (id) ON DELETE SET NULL,
  CONSTRAINT fk_hod_department FOREIGN KEY (department_id) REFERENCES department (id)    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS teacher_reg (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name    VARCHAR(100) NOT NULL,
  last_name     VARCHAR(100) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  phone         VARCHAR(20)  NOT NULL,
  password      VARCHAR(255) NOT NULL,
  report_to     INT NULL,
  department_id INT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_teacher_email UNIQUE (email),
  CONSTRAINT uq_teacher_phone UNIQUE (phone),
  CONSTRAINT fk_teacher_hod        FOREIGN KEY (report_to)     REFERENCES hod_reg (id)    ON DELETE SET NULL,
  CONSTRAINT fk_teacher_department FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL
);

-- Codes an admin hands to a new principal (checked on principal registration)
CREATE TABLE IF NOT EXISTS details (
  id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  principal_verification VARCHAR(64) NOT NULL,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_details_code UNIQUE (principal_verification)
);

-- ---------- Academic data ----------

CREATE TABLE IF NOT EXISTS student (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  roll_no        VARCHAR(30)  NOT NULL,
  first_name     VARCHAR(100) NOT NULL,
  last_name      VARCHAR(100) NOT NULL,
  email          VARCHAR(255) NOT NULL,
  phone          VARCHAR(20)  NOT NULL,
  password       VARCHAR(255) NOT NULL,
  gender         VARCHAR(10)  NULL,
  dob            DATE NULL,
  address        TEXT NULL,
  guardian_name  VARCHAR(150) NULL,
  guardian_phone VARCHAR(20)  NULL,
  department_id  INT NULL,
  semester       SMALLINT NOT NULL DEFAULT 1,
  status         VARCHAR(10) NOT NULL DEFAULT 'active',
  admitted_on    DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_student_roll  UNIQUE (roll_no),
  CONSTRAINT uq_student_email UNIQUE (email),
  CONSTRAINT uq_student_phone UNIQUE (phone),
  CONSTRAINT ck_student_sem    CHECK (semester BETWEEN 1 AND 12),
  CONSTRAINT ck_student_status CHECK (status IN ('active', 'inactive', 'graduated')),
  CONSTRAINT fk_student_department FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE SET NULL
);

-- A course is taught to every active student of the same department and semester
CREATE TABLE IF NOT EXISTS course (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          VARCHAR(20)  NOT NULL,
  name          VARCHAR(150) NOT NULL,
  department_id INT NOT NULL,
  semester      SMALLINT NOT NULL DEFAULT 1,
  credits       SMALLINT NOT NULL DEFAULT 3,
  teacher_id    INT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_course_code UNIQUE (code),
  CONSTRAINT ck_course_sem     CHECK (semester BETWEEN 1 AND 12),
  CONSTRAINT ck_course_credits CHECK (credits BETWEEN 1 AND 10),
  CONSTRAINT fk_course_department FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE,
  CONSTRAINT fk_course_teacher    FOREIGN KEY (teacher_id)    REFERENCES teacher_reg (id) ON DELETE SET NULL
);

-- P = present, A = absent, L = late (late counts as attended)
CREATE TABLE IF NOT EXISTS attendance (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id  INT NOT NULL,
  student_id INT NOT NULL,
  att_date   DATE NOT NULL,
  status     CHAR(1) NOT NULL,
  marked_by  VARCHAR(40) NULL,
  CONSTRAINT uq_attendance UNIQUE (course_id, student_id, att_date),
  CONSTRAINT ck_attendance_status CHECK (status IN ('P', 'A', 'L')),
  CONSTRAINT fk_att_course  FOREIGN KEY (course_id)  REFERENCES course (id)  ON DELETE CASCADE,
  CONSTRAINT fk_att_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_attendance_student ON attendance (student_id);
CREATE INDEX IF NOT EXISTS ix_attendance_date    ON attendance (att_date);

CREATE TABLE IF NOT EXISTS exam (
  id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id  INT NOT NULL,
  title      VARCHAR(120) NOT NULL,
  exam_date  DATE NOT NULL DEFAULT CURRENT_DATE,
  max_marks  SMALLINT NOT NULL DEFAULT 100,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_exam_max CHECK (max_marks > 0),
  CONSTRAINT fk_exam_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mark (
  exam_id    INT NOT NULL,
  student_id INT NOT NULL,
  marks      NUMERIC(6,2) NOT NULL,
  PRIMARY KEY (exam_id, student_id),
  CONSTRAINT fk_mark_exam    FOREIGN KEY (exam_id)    REFERENCES exam (id)    ON DELETE CASCADE,
  CONSTRAINT fk_mark_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notice (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       VARCHAR(200) NOT NULL,
  body        TEXT NOT NULL,
  audience    VARCHAR(10) NOT NULL DEFAULT 'all',
  author_role VARCHAR(10) NOT NULL,
  author_id   INT NOT NULL,
  author_name VARCHAR(200) NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT ck_notice_audience CHECK (audience IN ('all', 'staff', 'students'))
);

-- Reference data: departments (only inserted when missing)
INSERT INTO department (name, status) VALUES
  ('Computer Science', 0),
  ('Information Technology', 0),
  ('Electronics', 0),
  ('Mechanical Engineering', 0)
ON CONFLICT (name) DO NOTHING;
